name: Build Application
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependecies
        run: npm ci

      - name: Make a Zip
        run: npm run make

      - name: List Files
        run: ls
