name: Build Application
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependecies
        run: yarn

      - name: Make a Zip
        run: yarn make

      - name: List Files
        run: ls out/make/zip/win32

      # - name: Upload Zip to Google Drive
      #   uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      #   with:
      #     target: 'out'
      #     credentials: ${{secrets.GD_KEY}}
      #     parent_folder_id: 1D1mfKpD3izA3fitADnsz7fv-LGV92Kla
